//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedGraph {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZedGraphLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZedGraphLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZedGraph.Eto.ZedGraphLocale", typeof(ZedGraphLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image copied to clipboard.
        /// </summary>
        public static string copied_to_clip {
            get {
                return ResourceManager.GetString("copied_to_clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup....
        /// </summary>
        public static string page_setup {
            get {
                return ResourceManager.GetString("page_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As....
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Scale to Default.
        /// </summary>
        public static string set_default {
            get {
                return ResourceManager.GetString("set_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Point Values.
        /// </summary>
        public static string show_val {
            get {
                return ResourceManager.GetString("show_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title_def {
            get {
                return ResourceManager.GetString("title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo All Zoom/Pan.
        /// </summary>
        public static string undo_all {
            get {
                return ResourceManager.GetString("undo_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Pan.
        /// </summary>
        public static string unpan {
            get {
                return ResourceManager.GetString("unpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Scroll.
        /// </summary>
        public static string unscroll {
            get {
                return ResourceManager.GetString("unscroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Zoom.
        /// </summary>
        public static string unzoom {
            get {
                return ResourceManager.GetString("unzoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        public static string x_title_def {
            get {
                return ResourceManager.GetString("x_title_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis.
        /// </summary>
        public static string y_title_def {
            get {
                return ResourceManager.GetString("y_title_def", resourceCulture);
            }
        }
    }
}
